# Generated by Django 2.0 on 2017-12-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FangWenQingKuang',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ri_qi', models.DateTimeField(blank=True, null=True)),
                ('shang_pin_id', models.BigIntegerField()),
                ('zhuang_tai', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fang_wen_qing_kuang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeiMuDuiZhao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lei_mu_yuan', models.CharField(blank=True, max_length=50, null=True)),
                ('lei_mu', models.CharField(blank=True, max_length=50, null=True)),
                ('web_lei_mu', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lei_mu_dui_zhao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShangPinShuJu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shang_pin_id', models.BigIntegerField()),
                ('shang_pin_ming_cheng', models.CharField(blank=True, max_length=100, null=True)),
                ('tu_pian_di_zhi', models.CharField(blank=True, max_length=200, null=True)),
                ('shang_pin_lei_mu', models.CharField(blank=True, max_length=50, null=True)),
                ('tao_di_zhi', models.CharField(blank=True, max_length=400, null=True)),
                ('jia_ge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('yue_xiao_liang', models.IntegerField(blank=True, null=True)),
                ('yong_jin', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('shou_ru_bi_lv', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('quan_mian_e', models.IntegerField(blank=True, null=True)),
                ('kai_shi', models.DateField(blank=True, null=True)),
                ('jie_shu', models.DateField(blank=True, null=True)),
                ('quan_di_zhi', models.CharField(blank=True, max_length=400, null=True)),
                ('tian_jia_ri_qi', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shang_pin_shu_ju',
                'managed': False,
            },
        ),
    ]
